#!/bin/sh

echo "Updating submodules"
cd ~
cd dotfiles
git submodule init
git submodule update
sh ./laptop/mac

echo "Setting up symlinks"
ln -s ~/dotfiles/dotvim/zshrc ~/.zshrc
ln -s ~/dotfiles/dotvim/vimrc.local ~/.vimrc.local
ln -s ~/dotfiles/dotvim/vimrc.bundles.local ~/.vimrc.bundles.local
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/gitconfig ~/.gitconfig

echo "Setting up powerline font"
cp ~/dotfiles/dotvim/Monaco-Powerline.otf ~/Library/Fonts/

echo "Setting up oh-my-zsh powerline theme"
ln -s ~/dotfiles/oh-my-zsh-powerline-theme/powerline.zsh-theme ~/.oh-my-zsh/themes/powerline.zsh-theme
