#!/usr/bin/env zsh

git submodule init
git submodule update

echo "Setting up symlinks"
  ln -s ~/dotfiles/zshrc ~/.zshrc
  ln -s ~/dotfiles/vimrc.local ~/.vimrc.local
  ln -s ~/dotfiles/vimrc.before.local ~/.vimrc.before.local
  ln -s ~/dotfiles/vimrc.bundles.local ~/.vimrc.bundles.local
  ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
  ln -s ~/dotfiles/gitconfig ~/.gitconfig
  ln -s ~/dotfiles/gitignore ~/.gitignore
